services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_USER: 'waAdmin1'
      MYSQL_PASSWORD: 'changeme'
      MYSQL_DATABASE: 'wa2'
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
