-- Read-only preflight and verification queries for the CIWS formula backfill.
-- These statements do not modify data.

-- 1. Classify scored rows by source-data availability.
SELECT
  COUNT(*) AS scored_rows,
  SUM(Q_TOKEN_CORRECT IS NOT NULL
      AND Q_TOKEN_WORD IS NOT NULL
      AND Q_TOKEN_SEN_INACC IS NOT NULL
      AND Q_TOKEN_SEN_OVERLAP IS NOT NULL
      AND Q_TOKEN_SEN_NMAE IS NOT NULL) AS complete_token_rows,
  SUM((Q_TOKEN_CORRECT IS NOT NULL
       OR Q_TOKEN_WORD IS NOT NULL
       OR Q_TOKEN_SEN_INACC IS NOT NULL
       OR Q_TOKEN_SEN_OVERLAP IS NOT NULL
       OR Q_TOKEN_SEN_NMAE IS NOT NULL)
      AND NOT (Q_TOKEN_CORRECT IS NOT NULL
               AND Q_TOKEN_WORD IS NOT NULL
               AND Q_TOKEN_SEN_INACC IS NOT NULL
               AND Q_TOKEN_SEN_OVERLAP IS NOT NULL
               AND Q_TOKEN_SEN_NMAE IS NOT NULL)) AS partial_token_rows,
  SUM(Q_TOKEN_CORRECT IS NULL
      AND Q_TOKEN_WORD IS NULL
      AND Q_TOKEN_SEN_INACC IS NULL
      AND Q_TOKEN_SEN_OVERLAP IS NULL
      AND Q_TOKEN_SEN_NMAE IS NULL
      AND Q_SCORING IS NOT NULL
      AND Q_SCORING <> '') AS markup_only_rows,
  SUM(Q_TOKEN_CORRECT IS NULL
      AND Q_TOKEN_WORD IS NULL
      AND Q_TOKEN_SEN_INACC IS NULL
      AND Q_TOKEN_SEN_OVERLAP IS NULL
      AND Q_TOKEN_SEN_NMAE IS NULL
      AND (Q_SCORING IS NULL OR Q_SCORING = '')) AS unrecoverable_rows
FROM quiz
WHERE Q_SENTENCE_ERROR IS NOT NULL
   OR Q_SENTENCE_ACCURACY IS NOT NULL
   OR Q_CIWS IS NOT NULL;

-- 2. Source inconsistency: expected zero before applying.
SELECT COUNT(*) AS word_count_mismatches
FROM quiz
WHERE Q_WORD_ERROR IS NOT NULL
  AND Q_TOKEN_WORD IS NOT NULL
  AND Q_WORD_ERROR <> Q_TOKEN_WORD;

-- 3. Preview changed values for complete-token rows.
SELECT
  Q_ID,
  Q_SENTENCE_ERROR AS old_sentence_error,
  CASE
    WHEN Q_SENTENCE_ERROR IS NULL THEN NULL
    ELSE Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP
  END AS new_sentence_error,
  Q_SENTENCE_ACCURACY AS old_sentence_accuracy,
  CASE
    WHEN Q_SENTENCE_ACCURACY IS NULL THEN NULL
    WHEN Q_TOKEN_CORRECT + Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP = 0 THEN 0.000
    ELSE ROUND(
      1 - ((Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP)
           / (Q_TOKEN_CORRECT + Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP)),
      3
    )
  END AS new_sentence_accuracy,
  Q_CIWS AS old_ciws,
  CASE
    WHEN Q_CIWS IS NULL THEN NULL
    ELSE (CAST(Q_TOKEN_CORRECT AS SIGNED) + CAST(Q_TOKEN_SEN_NMAE AS SIGNED))
      - (CAST(Q_TOKEN_SEN_INACC AS SIGNED)
         + CAST(Q_TOKEN_SEN_OVERLAP AS SIGNED)
         + CAST(Q_TOKEN_WORD AS SIGNED))
  END AS new_ciws
FROM quiz
WHERE Q_TOKEN_CORRECT IS NOT NULL
  AND Q_TOKEN_WORD IS NOT NULL
  AND Q_TOKEN_SEN_INACC IS NOT NULL
  AND Q_TOKEN_SEN_OVERLAP IS NOT NULL
  AND Q_TOKEN_SEN_NMAE IS NOT NULL
  AND (Q_SENTENCE_ERROR IS NOT NULL
       OR Q_SENTENCE_ACCURACY IS NOT NULL
       OR Q_CIWS IS NOT NULL)
ORDER BY Q_ID
LIMIT 100;

-- 4. Post-apply invariant check: each result should be zero.
SELECT
  SUM(Q_SENTENCE_ERROR IS NOT NULL
      AND Q_SENTENCE_ERROR <> Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP)
      AS bad_sentence_error,
  SUM(Q_SENTENCE_ACCURACY IS NOT NULL
      AND Q_SENTENCE_ACCURACY <> CASE
        WHEN Q_TOKEN_CORRECT + Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP = 0 THEN 0.000
        ELSE ROUND(
          1 - ((Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP)
               / (Q_TOKEN_CORRECT + Q_TOKEN_SEN_INACC + Q_TOKEN_SEN_OVERLAP)),
          3
        )
  END) AS bad_sentence_accuracy,
  SUM(Q_CIWS IS NOT NULL
      AND Q_CIWS <> (CAST(Q_TOKEN_CORRECT AS SIGNED) + CAST(Q_TOKEN_SEN_NMAE AS SIGNED))
                     - (CAST(Q_TOKEN_SEN_INACC AS SIGNED)
                        + CAST(Q_TOKEN_SEN_OVERLAP AS SIGNED)
                        + CAST(Q_TOKEN_WORD AS SIGNED)))
      AS bad_ciws
FROM quiz
WHERE Q_TOKEN_CORRECT IS NOT NULL
  AND Q_TOKEN_WORD IS NOT NULL
  AND Q_TOKEN_SEN_INACC IS NOT NULL
  AND Q_TOKEN_SEN_OVERLAP IS NOT NULL
  AND Q_TOKEN_SEN_NMAE IS NOT NULL
  AND (Q_SENTENCE_ERROR IS NOT NULL
       OR Q_SENTENCE_ACCURACY IS NOT NULL
       OR Q_CIWS IS NOT NULL);
